build same version

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -25,31 +25,31 @@ jobs:
         with:
           node-version: 18
 
-      - name: Install Firebase CLI
-        run: |
-          npm install -g firebase-tools
+      # - name: Install Firebase CLI
+      #   run: |
+      #     npm install -g firebase-tools
 
-      - name: Install aapt
-        run: |
-          sudo apt-get update
-          sudo apt-get install -y android-sdk-build-tools
+      # - name: Install aapt
+      #   run: |
+      #     sudo apt-get update
+      #     sudo apt-get install -y android-sdk-build-tools
 
-      - name: Check Firebase App Version
-        id: check_version
-        run: |
-          # Get the latest version from Firebase
-          latest_version=$(firebase appdistribution:versions:list --app ${{secrets.FIREBASE_APP_ID}} --token "$FIREBASE_TOKEN" --format "value(version)" | head -n 1)
+      # - name: Check Firebase App Version
+      #   id: check_version
+      #   run: |
+      #     # Get the latest version from Firebase
+      #     latest_version=$(firebase appdistribution:versions:list --app ${{secrets.FIREBASE_APP_ID}} --token "$FIREBASE_TOKEN" --format "value(version)" | head -n 1)
 
-          # Get the version of the APK you are trying to deploy
-          new_version=$(aapt dump badging app-release.apk | awk -F"'" '/versionName/{print $2}')
+      #     # Get the version of the APK you are trying to deploy
+      #     new_version=$(aapt dump badging app-release.apk | awk -F"'" '/versionName/{print $2}')
 
-          echo "Latest version from Firebase: $latest_version"
-          echo "New version of the APK: $new_version"
+      #     echo "Latest version from Firebase: $latest_version"
+      #     echo "New version of the APK: $new_version"
 
-          if [ "$latest_version" == "$new_version" ]; then
-          echo "Error: The new app version is the same as the current last app version in Firebase."
-          exit 1
-          fi
+      #     if [ "$latest_version" == "$new_version" ]; then
+      #     echo "Error: The new app version is the same as the current last app version in Firebase."
+      #     exit 1
+      #     fi
 
       - name: Deploy
         uses: wzieba/Firebase-Distribution-Github-Action@v1.7.0
